import:
  - ~/src/github.com/dracula/alacritty/dracula.yml

window:
  decorations: none
  dynamic_title: true

scrolling:
  history: 10000
  multiplier: 3

font:
  size: 12.0
  normal:
    family: JetBrainsMono Nerd Font

mouse:
  hide_when_typing: true
  url:
    launcher:
      program: xdg-open

