[
  ./desktop
  ./desktop/awesome.nix
  ./desktop/bspwm.nix
  ./desktop/i3.nix
  ./desktop/xmonad.nix
  ./desktop/programs/alacritty.nix
  ./desktop/programs/brave.nix
  ./desktop/programs/chrome.nix
  ./desktop/programs/compton.nix
  ./desktop/programs/dunst.nix
  ./desktop/programs/firefox.nix
  ./desktop/programs/picom.nix
  ./desktop/programs/polybar.nix
  ./desktop/programs/rofi.nix
  ./desktop/programs/termite.nix
  ./desktop/programs/thunderbird.nix
  ./dev/android.nix
  ./dev/c.nix
  ./dev/elixir.nix
  ./dev/elm.nix
  ./dev/go.nix
  ./dev/godot.nix
  ./dev/guile.nix
  ./dev/haskell.nix
  ./dev/idris.nix
  ./dev/javascript.nix
  ./dev/latex.nix
  ./dev/lua.nix
  ./dev/mysql.nix
  ./dev/ocaml.nix
  ./dev/php.nix
  ./dev/plantuml.nix
  ./dev/python.nix
  ./dev/ruby.nix
  ./dev/rust.nix
  ./dev/web.nix
  ./editors/emacs
  ./editors/neovim.nix
  ./editors/vscode.nix
  ./media/plex.nix
  ./media/spotify.nix
  ./network.nix
  ./services/bitwarden.nix
  ./services/fingerprint.nix
  ./services/fwupd.nix
  ./services/gpg.nix
  ./services/guix.nix
  ./services/keyring.nix
  ./services/libvirtd.nix
  ./services/mail.nix
  ./services/postgres.nix
  ./services/ssh.nix
  ./services/syncthing.nix
  ./services/virtualbox.nix
  ./services/zerotier.nix
  ./shell/direnv.nix
  ./shell/fish.nix
  ./shell/git.nix
  ./shell/starship.nix
  ./shell/zsh.nix
  ./social/discord.nix
  ./social/keybase.nix
  ./social/riot.nix
  ./social/signal.nix
  ./social/slack.nix
  ./tools
  ./tools/aws.nix
  ./tools/build.nix
  ./tools/devops.nix
  ./tools/docker.nix
  ./tools/insomnia.nix
  ./tools/light.nix
  ./tools/podman.nix
  ./tools/sql.nix
]
