[identities]
ochatt = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKdGuXrkHZdLl/+/kTxtbByYyxhLpcMTzfx3fABK6qt4"
vercar = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMO6/jzKplTgI8UEbJTdNskExUfQEJ9GG1b9smYXoaP4"
beehum = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAR8+m6kSrZ8Zc3+NMolR2mzmfgzFPhij/cGl2KGHDBQ"

[groups]
users = [ "ochatt", "beehum" ]
servers = [ "vercar" ]
admins = [ "ochatt", "beehum" ]

[[paths]]
glob = "secrets/vercar/**"
identities = [ "vercar" ]
groups = [ "admins" ]