tap "babariviere/tools", "git@github.com:babariviere/homebrew-tools.git"
tap "d12frosted/emacs-plus"
tap "fewlinesco/tap"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "proxmark/proxmark3"
brew "asciidoctor"
brew "autoconf"
brew "automake"
brew "bat"
brew "openssl@1.1"
brew "python@3.8"
brew "circleci"
brew "cmake"
brew "coreutils"
brew "libtool"
brew "crosstool-ng"
brew "direnv"
brew "dog"
brew "dotnet"
brew "wxmac"
brew "elixir"
brew "node"
brew "exa"
brew "fd"
brew "findutils"
brew "flow"
brew "fswatch"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "gnupg"
brew "go"
brew "graphviz"
brew "helm"
brew "hivemind"
brew "htop"
brew "httpie"
brew "hub"
brew "ipfs"
brew "jq"
brew "kubernetes-cli", link: false
brew "kubeseal"
brew "languagetool"
brew "lazygit"
brew "libxslt"
brew "libyaml"
brew "luajit", args: ["HEAD"]
brew "luarocks"
brew "mas"
brew "mkcert"
brew "mkdocs"
brew "neovim", args: ["HEAD"]
brew "nginx"
brew "nnn"
brew "nss"
brew "oil"
brew "openapi-generator"
brew "tmux", args: ["HEAD"]
brew "overmind"
brew "pandoc"
brew "pgcli"
brew "pinentry-mac"
brew "poetry"
brew "postgresql"
brew "prettier"
brew "pygments"
brew "qemu"
brew "rcm"
brew "recon-ng"
brew "ripgrep"
brew "sd"
brew "shellcheck"
brew "socat"
brew "starship"
brew "tealdeer"
brew "thefuck"
brew "tokei"
brew "tree"
brew "unixodbc"
brew "unrar"
brew "watch"
brew "wget"
brew "yarn"
brew "babariviere/tools/flow-sh", link: false
brew "d12frosted/emacs-plus/emacs-plus@27", args: ["with-modern-sexy-v2-icon"]
brew "fewlinesco/tap/fwl_error"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "proxmark/proxmark3/proxmark3", args: ["HEAD"]
cask "1password"
cask "1password-cli"
cask "alfred"
cask "altair-graphql-client"
cask "clickup"
cask "dash"
cask "discord"
cask "docker"
cask "encryptme"
cask "eul"
cask "firefox"
cask "font-blex-mono-nerd-font"
cask "font-caskaydia-cove-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-ia-writer-mono"
cask "font-im-writing-nerd-font"
cask "font-inter"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-ubuntu-mono-nerd-font"
cask "gpg-suite-no-mail"
cask "hammerspoon"
cask "inkscape"
cask "insomnia"
cask "ipfs"
cask "istat-menus"
cask "karabiner-elements"
cask "onecast"
cask "postico"
cask "slack"
cask "spotify"
cask "tableplus"
cask "transmission"
cask "visual-studio-code"
mas "AdGuard for Safari", id: 1440147259
mas "Aviary", id: 1522043420
mas "Dark Reader for Safari", id: 1438243180
mas "GoodNotes", id: 1444383602
mas "Grammarly for Safari", id: 1462114288
mas "Userscripts", id: 1463298887
mas "Xcode", id: 497799835
