---
files:
  - path: ".bin"
    location: home
    recursive: true
    exclude:
      - trm
  - path: alacritty
    location: config
    recursive: true
  - path: dunst
    location: config
    recursive: true
  - path: i3
    location: config
    recursive: true
  - path: i3blocks
    location: config
    recursive: true
  - path: polybar
    location: config
    recursive: true
  - path: termite
    location: config
    recursive: true
  - path: yay
    location: config
    recursive: true
  - path: zathura
    location: config
    recursive: true
  - path: ".xres"
    location: home
    recursive: true
  - path: ".Xresources"
    location: home
  - path: ".clang-format"
    location: home
  - path: ".profile"
    location: home
  - path: coc/extensions/package.json
    location: config
  - path: fish/local
    location: config
    recursive: true
  - path: fish/fishfile
    location: config
  - path: ".zsh"
    location: home
    recursive: true
    exclude:
      - history
  - path: fish/config.fish
    location: config
  - path: ".cargo/config"
    location: home
  - path: ".elvish"
    location: home
    recursive: true
    exclude:
      - lib/**
      - db
      - lib
  - path: /usr/local/bin
    location: absolute
    recursive: true
  - path: nvim
    location: config
    recursive: true
    exclude:
      - spell/*
      - ".netrwhist"
  - path: mako
    location: config
    recursive: true
  - path: sway
    location: config
    recursive: true
  - path: waybar
    location: config
    recursive: true
git:
  path: ".dot/.git"
  location: home
dot: ~