#+TITLE:   dotfiles
#+DATE:    October 27, 2019

Repository of my personal dotfiles.
This targets Nix/NixOS users.

* Table of Contents :TOC_3:noexport:
- [[#usage][Usage]]
- [[#description][Description]]
  - [[#hosts][Hosts]]
  - [[#hardware][Hardware]]
  - [[#modules][Modules]]
  - [[#profiles][Profiles]]
- [[#screenshots][Screenshots]]

* Usage

#+BEGIN_SRC sh
# Clone repository in your favorite location
git clone https://github.com/babariviere/dotfiles
cd dotfiles

# Link it to /etc/nixos
sudo ln -s $(pwd) /etc/nixos

# Install it via nix flakes, replace host by one of the file in `hosts` (except for default.nix)
sudo nix-shell -p nixFlakes --run nixos-rebuild switch -p "<host>"
#+END_SRC

To update flake: =nix flake update --recreate-lock-file=

* Description
** Hosts
A configuration for an host or a machine. It's where we use all the modules and profiles.
All files (except ~default.nix~) in ~hosts~ is considered as an host
and can be built via ~nixos-rebuild switch -p <host>~ or via ~nix shell .#nixosConfiguration.<host>~.

** Hardware
It's the hardware configuration for each host. They are imported from ~hosts~ files.

They are generated via ~nixos-generate-config --show-hardware-config~. It generally includes:
+ kernel version
+ boot arguments
+ file system configuration
+ swap devices
+ CPU configuration

** Modules
A list of custom modules made to create an explicit configuration with dependencies.

For example: if I set ~dotfiles.dev.rust.enable~ to ~true~, emacs will generate a configuration
to enable rust syntax highlighting and code completion.

All modules must have an option set with an enable flag. Otherwise, it should be put in ~profiles~.
There are all declared in ~modules/list.nix~ and exported via ~nixosModules~ in ~flake.nix~.

** Profiles
A list of common configurations that does not requires configuration (unlike modules).
There are all declared in ~profiles/list.nix~ and exported via ~nixosModules~ in ~flake.nix~.

* Screenshots
TODO: include screenshot for each system
