#!/usr/bin/env bash

# MONITOR=$(xrandr -q | grep primary | grep ' connected' | cut -d' ' -f1)
bspc monitor "eDP-1-1" -d I II III IV V

#
# UI
# 
bspc config split_ratio 0.50
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config paddingless_monocle true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config normal_border_color @background@
bspc config active_border_color @foreground@
bspc config focused_border_color @foreground@
bspc config urgent_border_color @red@

bspc config border_width 2
bspc config window_gap 8
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

#
# Rules
#

bspc rule -r '*'

bspc rule -a Emacs state=tiled

# Desktop
bspc rule -a discord desktop=^3 state=tiled
bspc rule -a Slack desktop=^3
bspc rule -a Firefox desktop=^1

pkill polybar
@launchPolybar@
@setWallpaper@
