name: "Build"
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          install_url: nixos-nix-install-tests.cachix.org/serve/v936a7w28x1zlv6qh2hc17sbfqf30zj5/install
          install_options: --tarball-url-prefix nixos-nix-install-tests.cachix.org/serve
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            sandbox = relaxed
            allowed-impure-host-deps = /usr/bin/osacompile
      - uses: cachix/cachix-action@v10
        with:
          name: babariviere
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build packages
        run: nix build .#emacsGit .#amber-emacs -L
      - name: Build ochatt
        run: nix build .#darwinConfigurations.ochatt.system -L
