name: "Build"
on: [workflow_dispatch, push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/8d8xah1f6ypccpmw9cfsl8ziw1chj4cl/install
          install_options: --tarball-url-prefix nixos-nix-install-tests.cachix.org/serve
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            sandbox = relaxed
      - uses: cachix/cachix-action@v10
        with:
          name: babariviere
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build packages
        run: nix build .#emacsGit .#amber-emacs -L
      - name: Build emacs-client (in non-sandbox)
        run: nix build .#emacs-client --option sandbox false
      - name: Build ochatt
        run: nix build .#darwinConfigurations.ochatt.system -L
