name: "check flake"
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/8d8xah1f6ypccpmw9cfsl8ziw1chj4cl/install
          install_options: --tarball-url-prefix nixos-nix-install-tests.cachix.org/serve
          extra_nix_config: |
            experimental-features = nix-command flakes
            sandbox = relaxed
      - name: check flake
        run: nix flake check
